Fix `AttributeError: 'NoneType' object has no attribute 'value'` for `mv == None`
Also fixes "DeprecationWarning: elementwise comparison failed", which previously happened for `frame == None`.
After the change to `mv == None` this raises `ValueError`, and the fix is to use `frame is None` instead.