Fix `layout.parse_multivector` to not produce nonsense
Now:
* Supports unusual basis names
* Gives error messages instead of producing zeros
  ```python
  >>> layout.parse_multivector("e3 + whoops")
  Traceback (most recent call last):
    File "<string>", line 1
      e3 + whoops
           ^
  SyntaxError: Unexpected unrecognized token after sign
  ```
Before:
```
>>> layout.parse_multivector("2e+1^e3")
(20.0^e3)
>>>  layout.parse_multivector("2.e+1^e3")
(1.0^e3)  # wat
>>>  layout.parse_multivector("2.e+1")
0  # wat
>>> layout.parse_multivector("e1")
0  # wat
```